name: Run Spam Script

on:
  workflow_dispatch:
    inputs:
      sdt:
        description: "Nhập số điện thoại"
        required: true
      so_lan_spam:
        description: "Nhập số lần spam"
        required: true
      so_lan_chay_song_song:
        description: "Nhập số tiến trình chạy song song"
        required: true

jobs:
  run-spam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run run_spam.py
        run: python run_spam.py "${{ github.event.inputs.sdt }}" "${{ github.event.inputs.so_lan_spam }}" "${{ github.event.inputs.so_lan_chay_song_song }}"
